feat: have `landscape-config --silent` only send a registration messa…
canonical/landscape-client pull request #258
Opened 2024-08-05 18:11 UTC by wck0

…ge when required and add a new `--force-registration` flag

2024-08-05 18:24 UTC, wck0 commented
Currently, `landscape-config --silent` will always try to send a registration message. With this change, when the `--silent` flag is set we only send the registration message if we can deduce that no registration message has been sent yet (i.e. the secure id is null), or the `landscape-config` is explicitly called with the `--force-registration` flag.

Manual testing instructions:

1. Working on this branch, configure Landscape Client and have it send a registration message to create a new pending computer.
2. Run `landscape-config --silent` and observe no additional pending computer is created.
3. Accept the pending computer and allow some message exchange to occur.
4. Run `landscape-config --silent` and observe no additional pending computer is created.
5. Run `landscape-config --silent --force-registration` and observe no additional pending computer is created.

Repeat ad nauseam making changes to the configuration along the way.

2024-08-05 21:23 UTC, srunde3 commented
Why do we want `--force-registration` to *not* create a new pending computer?  Wouldn't we want it to create a new secure_id for the client and therefore a new pending computer?

2024-08-05 21:24 UTC, srunde3 reviewed
Manual testing went fine according to your instructions; left one question about if your documented behavior is what we "want" from this change

2024-08-05 21:26 UTC, silverdrake11 commented
How is this different from this pull request https://github.com/canonical/landscape-client/pull/243

2024-08-05 21:32 UTC, silverdrake11 commented
One other question. Will this break existing scripts that rely on landscape-config sending a new registration as the default behavior? I can see that the charm will be affected by this. For example, if the user runs the re-register run action, then that is implement simply by a `landscape-config --silent`

2024-08-05 21:44 UTC, wck0 commented
> Why do we want `--force-registration` to _not_ create a new pending computer? Wouldn't we want it to create a new secure_id for the client and therefore a new pending computer?

We don't. I made a copy-pasta error in my testing instructions. Editing them to better reflect the intentions.

2024-08-05 21:46 UTC, wck0 commented
> How is this different from this pull request #243

The `--skip-registration` flag can be passed independent of the `--silent` flag.

2024-08-05 21:47 UTC, wck0 commented
> One other question. Will this break existing scripts that rely on landscape-config sending a new registration as the default behavior? I can see that the charm will be affected by this. For example, if the user runs the re-register run action, then that is implement simply by a `landscape-config --silent`

Yes, it sounds like this change will break that behavior. It can be adjusted in the charm by calling `landscape-config --silent --force-registration` if the charm action should always result in a new registration request.

2024-08-05 21:56 UTC, silverdrake11 commented
In that case I would prefer we have a flag `--send-only-if-unsent` (maybe we can think of a better name) than modify the default behavior of landscape client. We have alot of customers relying on old default behavior and changing the api in a way that could result in breaking changes seems like it can cause trouble

2024-08-06 00:08 UTC, wck0 commented
OK, good point. I'll fix this up and let Carlos know.

2024-08-06 00:11 UTC, wck0 commented
Leaning towards `--register-if-needed` but open to suggestions.

2024-08-06 23:13 UTC, wck0 commented
Updated, restoring the behavior of `--silent` and with a new flag `--register-if-needed`.
Other refactoring, too.

2024-08-06 23:14 UTC, wck0 commented on landscape/client/configuration.py
> -        registration_status = is_registered(config)
I think I picked this nit.

2024-08-08 23:18 UTC, srunde3 reviewed
Code looks good, but I'm getting unexpected registration messages after running `--silent --register-if-needed`.  I'll continue this tomorrow to see if the issue exists between chair and keyboard or if changes are needed here.

2024-08-09 17:58 UTC, srunde3 requested changes

2024-08-13 18:19 UTC, wck0 commented
Updated. For manual testing now:

1.  start with a fresh snap install
2. register with your Landscape Server
3. accept the pending computer
4. wait for message exchange to occur. This ensures that the `secure_id` is set on the client to match the accepted computer
5. inspect the `broker.bpickle` file and note the value of `secure_id`
6. run `landscape-config --silent --register-if-needed`
7. observe no new pending computer is created.
8. inspect the `broker.bpickle` file and note that the value of `secure_id` has not changed
9. try to break something

2024-08-13 20:02 UTC, srunde3 commented on landscape/client/configuration.py
> +    if config.force_registration:
nit: you could rearrange this block to make it simpler, if you so desire:

```py
    if config.force_registration:
        should_register = True
    elif config.register_if_needed:
        should_register = not already_registered
    elif config.silent:
        should_register = True
    else:
        ...
```

2024-08-13 20:07 UTC, srunde3 approved these changes
LGTM! :ship: left one pedantic inline nit for your viewing pleasure.  Manual testing went well.

2024-08-14 00:05 UTC, merged