Add livepatch to manager instead of monitor, refactored
canonical/landscape-client pull request #260
Opened 2024-08-06 20:57 UTC by silverdrake11

2024-08-06 20:57 UTC, silverdrake11 commented
Note this is still drafting because to test, it requires landscapes server changes

2024-08-12 20:08 UTC, srunde3 requested changes
In addition to inline comments:

You may want these plugins included in the defaults for the landscape client snap.  See `snap/hooks/default-configure`

2024-08-13 23:15 UTC, silverdrake11 commented
> In addition to inline comments:
> 
> You may want these plugins included in the defaults for the landscape client snap. See `snap/hooks/default-configure`

I'll just add UbuntuProInfo for now. Which is strange that it's not there since there was this pull request recently to enable it for the snap https://github.com/canonical/landscape-client/commit/b2ce9c851cb6fecff945d286a5ca685cbaeca74e

2024-08-13 23:25 UTC, silverdrake11 commented on landscape/client/manager/tests/test_livepatch.py
> +            self.monitor.add(plugin)
Ok good point I updated

2024-08-15 14:57 UTC, srunde3 approved these changes
LGTM :ship: :hippopotamus:

2024-08-15 16:45 UTC, merged